### ISSUE TITLE
Add sort-keys rule

### ISSUE THREAD

**Issue by naltatis** [ota-meshi/eslint-plugin-toml#126]
I'd like to have a rule that ensures that tables and keys are in alphabetical order. Similar to e.g [jsonc/sort-keys](https://ota-meshi.github.io/eslint-plugin-jsonc/rules/sort-keys.html#jsonc-sort-keys).

```toml
# ✓ GOOD
[alpha]
y = 2
z = 3

[beta]
x = 1

# ✗ BAD
[beta]
x = 1

[alpha]
z = 3
y = 2
```
